site_name: Palgogo github.io
site_url: https://blog.palgogo.com/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Home: index.md
  - Notes:
      - Overview: notes/index.md
      - What a Platform Team Actually Buys You: notes/what-a-platform-team-buys-you.md
  - About: about.md
  - Projects: projects.md
  - Contact: contact.md
